all: test 


test: build
	dotnet test --no-build ./Test.J3DI.Domain
	dotnet test --no-build ./Test.J3DI.Infrastructure.EntityFactoryFx
	dotnet test --no-build ./Test.J3DI.Infrastructure.RepositoryFx


## based on https://github.com/coverlet-coverage/coverlet/issues/262#issuecomment-569572522:
##	MergeWith only works with json (coverlet's native format). On the last test, output cobertura fmt
##	Tests need to be run separately rather than via sln file
cover: build
	dotnet test --no-build Test.J3DI.Domain/Test.J3DI.Domain.csproj  --framework net8.0 --logger:trx --results-directory ../TestResults \
		"/p:Exclude=\"[Test.J3DI.*]*\"" \
 		"/p:ExcludeByAttribute=\"TestSDKAutoGeneratedCode,AutoGeneratedCode\" " \
 		"/p:CollectCoverage=true" \
		"/p:CoverletOutput=../TestResults/" \
		"/p:MergeWith=../TestResults/coverage.net8.0.json" \
		"/p:CoverletOutputFormat=\"json\"" 
	dotnet test --no-build Test.J3DI.Infrastructure.EntityFactoryFx/Test.J3DI.Infrastructure.EntityFactoryFx.csproj  --framework net8.0 --logger:trx --results-directory ../TestResults \
		"/p:Exclude=\"[Test.J3DI.*]*\"" \
 		"/p:ExcludeByAttribute=\"TestSDKAutoGeneratedCode,AutoGeneratedCode\" " \
		"/p:CollectCoverage=true" \
		"/p:CoverletOutput=../TestResults/" \
		"/p:MergeWith=../TestResults/coverage.net8.0.json" \
		"/p:CoverletOutputFormat=\"json\"" 
	dotnet test --no-build Test.J3DI.Infrastructure.RepositoryFx/Test.J3DI.Infrastructure.RepositoryFx.csproj  --framework net8.0 --logger:trx --results-directory ../TestResults \
		"/p:Exclude=\"[Test.J3DI.*]*\"" \
 		"/p:ExcludeByAttribute=\"TestSDKAutoGeneratedCode,AutoGeneratedCode\" " \
		"/p:CollectCoverage=true" \
		"/p:CoverletOutput=../TestResults/" \
		"/p:MergeWith=../TestResults/coverage.net8.0.json" \
		"/p:CoverletOutputFormat=\"json,cobertura\"" 


cover-report:
	reportgenerator \
		-targetdir:coveragereport/net8.0 \
		"-reports:./TestResults/coverage.net8.0.cobertura.xml"


coveralls-report:
	coveralls report --format=cobertura TestResults/coverage.net8.0.cobertura.xml --repo-token=XK3p5o0AoS4H838oiS9bvVwz4ibcLIkvp
	# coveralls report --format=lcov Test.J3DI.Domain/coverage.net8.0.info --repo-token=XK3p5o0AoS4H838oiS9bvVwz4ibcLIkvp
	# coveralls report --format=lcov Test.J3DI.Infrastructure.RepositoryFx/coverage.net8.0.info --repo-token=XK3p5o0AoS4H838oiS9bvVwz4ibcLIkvp
	# coveralls report --format=lcov Test.J3DI.Infrastructure.EntityFactoryFx/coverage.net8.0.info --repo-token=XK3p5o0AoS4H838oiS9bvVwz4ibcLIkvp


build: 
	dotnet build


clean:
	dotnet clean


clean-all: clean
	@echo "### Remove all NuPkg files"
	find . -iname "*.nupkg" -exec rm {} \;
	@echo "### Remove codecov files, coverage.net*"
	find . -name "coverage.net*" -exec rm -f {} \;
	@echo "### Remove coveragereport/*"
	rm -fr coveragereport/*
	@echo "### Remove TestResults/*"
	rm -fr TestResults/*
	# Last b/c sometimes fails
	@echo "### Remove bin and obj dirs"
	find . -type d -name "bin" -prune -exec rm -fr "{}" \;
	find . -type d -name "obj" -prune -exec rm -fr {} \;
