name: .NET Core Builds

on:
  push:
    branches: [ '*', '!master' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        build-config: [ Debug, Release ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.*
  
    - name: Install dependencies
      run: dotnet restore

    - name: Install tools
      run: dotnet tool restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.build-config }}

    - name: Test.J3DI.Domain
      run: dotnet test --no-restore --configuration ${{ matrix.build-config }} --verbosity normal ./Test.J3DI.Domain/Test.J3DI.Domain.csproj

    - name: Test.J3DI.Infrastructure.EntityFactoryFx
      run: dotnet test --no-restore --configuration ${{ matrix.build-config }} --verbosity normal ./Test.J3DI.Infrastructure.EntityFactoryFx/Test.J3DI.Infrastructure.EntityFactoryFx.csproj

    - name: Test.J3DI.Infrastructure.RepositoryFx
      run: dotnet test --no-restore --configuration ${{ matrix.build-config }} --verbosity normal ./Test.J3DI.Infrastructure.RepositoryFx/Test.J3DI.Infrastructure.RepositoryFx.csproj
