name: .NET Core Builds

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test.J3DI.Domain
      run: dotnet test --no-restore --verbosity normal ./Test.J3DI.Domain/Test.J3DI.Domain.csproj

    - name: Test.J3DI.Infrastructure.EntityFactoryFx
      run: dotnet test --no-restore --verbosity normal ./Test.J3DI.Infrastructure.EntityFactoryFx/Test.J3DI.Infrastructure.EntityFactoryFx.csproj

    - name: Test.J3DI.Infrastructure.RepositoryFx
      run: dotnet test --no-restore --verbosity normal ./Test.J3DI.Infrastructure.RepositoryFx/Test.J3DI.Infrastructure.RepositoryFx.csproj
