name: .NET Core 3.1

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal Test.J3DI.Domain/Test.J3DI.Domain.csproj && \
          dotnet test --no-restore --verbosity normal Test.J3DI.Infrastructure.EntityFactoryFx/Test.J3DI.Infrastructure.EntityFactoryFx.csproj && \
          dotnet test --no-restore --verbosity normal Test.J3DI.Infrastructure.RepositoryFx/Test.J3DI.Infrastructure.RepositoryFx.csproj
